# Generated by Django 4.2 on 2026-02-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic_app.jobrole'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='diagnostic_app.jobrole'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
