# Generated by Django 4.2 on 2026-02-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0002_alter_notification_job_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q0_budget_alignment',
            field=models.BooleanField(blank=True, help_text='Is this role accounted for in the current fiscal year budget?', null=True, verbose_name='Aligned with Annual Budget'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q0_cash_flow_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate the impact on cash flow (1=Negative, 5=Positive)', null=True, verbose_name='Cash Flow Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q0_funding_source',
            field=models.CharField(blank=True, choices=[('operational', 'Operational Budget'), ('contingency', 'Contingency Fund'), ('new_funding', 'Requires New Funding'), ('cost_center', 'Cost Center Budget')], max_length=50, null=True, verbose_name='Funding Source'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q0_roi_analysis',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate the projected ROI (1=Very Low, 5=Very High)', null=True, verbose_name='ROI Projection Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('co_founder', 'Co-Founder'), ('ceo', 'CEO'), ('cfo', 'CFO'), ('cto', 'CTO / Tech Lead'), ('coo', 'COO'), ('project_head', 'Project Head / Team Lead'), ('hr_manager', 'HR Manager / People Operations'), ('recruiter', 'Recruiter'), ('hr_executive', 'HR Executive')], max_length=20),
        ),
    ]
