# Generated by Django 4.2.28 on 2026-02-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0004_add_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_complementary_skills',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How complementary are the skills to existing team? (1=Overlap, 5=Highly Complementary)', null=True, verbose_name='Complementary Skills'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_culture_fit',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well aligned with company culture and values? (1=Poor, 5=Excellent)', null=True, verbose_name='Culture and Values Alignment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_decision_making',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True, verbose_name='Decision-Making Alignment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_partnership_dynamics',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well does this role complement partnership dynamics? (1=Poor, 5=Excellent)', null=True, verbose_name='Partnership Dynamics'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_team_chemistry',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well will this role integrate with team chemistry? (1=Poor, 5=Excellent)', null=True, verbose_name='Team Chemistry'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_equity_consideration',
            field=models.CharField(blank=True, choices=[('not_applicable', 'Not Applicable'), ('equity_required', 'Equity Required'), ('cash_only', 'Cash Only'), ('hybrid', 'Hybrid (Cash + Equity)')], max_length=20, null=True, verbose_name='Equity Consideration'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_market_positioning',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How does this role strengthen market positioning? (1=Weak, 5=Strong)', null=True, verbose_name='Market Positioning Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_resource_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True, verbose_name='Resource Allocation Priority'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_strategic_fit',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well does this role fit strategic goals? (1=Poor Fit, 5=Perfect Fit)', null=True, verbose_name='Strategic Fit'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_vision_alignment',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well does this role align with your company vision? (1=Poor, 5=Excellent)', null=True, verbose_name='Vision Alignment'),
        ),
    ]
