# Generated by Django 4.2.28 on 2026-02-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0005_add_founder_cofounder_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_board_alignment',
            field=models.CharField(blank=True, choices=[('aligned', 'Aligned'), ('neutral', 'Neutral'), ('concern', 'Concern')], max_length=10, null=True, verbose_name='Board/Investor Alignment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_cross_functional_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role affect multiple departments? (1=Low, 5=High)', null=True, verbose_name='Cross-functional Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_leadership_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role drive organizational success? (1=Low, 5=High)', null=True, verbose_name='Leadership Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_strategic_priority',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')], max_length=10, null=True, verbose_name='Strategic Priority Level'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_success_metrics',
            field=models.BooleanField(blank=True, help_text='Are success metrics clearly defined?', null=True, verbose_name='Success Metrics Available'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_budget_flexibility',
            field=models.CharField(blank=True, choices=[('flexible', 'Flexible'), ('limited', 'Limited'), ('fixed', 'Fixed')], max_length=10, null=True, verbose_name='Budget Flexibility'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_cash_flow_impact',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, null=True, verbose_name='Cash Flow Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_compliance',
            field=models.BooleanField(blank=True, help_text='Are compliance requirements satisfied?', null=True, verbose_name='Compliance Requirements Met'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_financial_risk',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How financially sound is this investment? (1=High Risk, 5=Low Risk)', null=True, verbose_name='Financial Risk Assessment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_roi_confidence',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How confident are you in financial returns? (1=Low, 5=Very High)', null=True, verbose_name='ROI Confidence'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_operational_efficiency',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role improve operational efficiency? (1=Low, 5=High)', null=True, verbose_name='Operational Efficiency'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_process_integration',
            field=models.CharField(blank=True, choices=[('seamless', 'Seamless'), ('moderate', 'Moderate'), ('complex', 'Complex')], max_length=10, null=True, verbose_name='Process Integration Level'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_resource_optimization',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well will this role optimize resources? (1=Low, 5=High)', null=True, verbose_name='Resource Optimization'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_standardization',
            field=models.BooleanField(blank=True, help_text='Are there standardization opportunities?', null=True, verbose_name='Standardization Opportunities'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_workflow_disruption',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True, verbose_name='Workflow Disruption Risk'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_innovation_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much will this role drive innovation? (1=Low, 5=High)', null=True, verbose_name='Innovation Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_scalability',
            field=models.BooleanField(blank=True, help_text='Are scalability requirements satisfied?', null=True, verbose_name='Scalability Requirements Met'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_stack_alignment',
            field=models.CharField(blank=True, choices=[('aligned', 'Aligned'), ('partial', 'Partial'), ('misaligned', 'Misaligned')], max_length=10, null=True, verbose_name='Technology Stack Alignment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_tech_debt',
            field=models.CharField(blank=True, choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact')], max_length=10, null=True, verbose_name='Technical Debt Considerations'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_technical_feasibility',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How technically achievable are objectives? (1=Low, 5=High)', null=True, verbose_name='Technical Feasibility'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_culture_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role affect team culture and morale? (1=Negative, 5=Positive)', null=True, verbose_name='Team Culture Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_development_potential',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10, null=True, verbose_name='Employee Development Potential'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_performance_integration',
            field=models.CharField(blank=True, choices=[('seamless', 'Seamless'), ('moderate', 'Moderate'), ('complex', 'Complex')], max_length=10, null=True, verbose_name='Performance Management Integration'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_retention_risk',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='What is the risk of current team members leaving? (1=High Risk, 5=Low Risk)', null=True, verbose_name='Retention Risk Assessment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_training_infrastructure',
            field=models.BooleanField(blank=True, help_text='Is training infrastructure available?', null=True, verbose_name='Training Infrastructure Available'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_compliance_status',
            field=models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('partial', 'Partial'), ('non_compliant', 'Non-Compliant')], max_length=15, null=True, verbose_name='Compliance Requirements Status'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_documentation',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How complete is our role documentation? (1=Incomplete, 5=Complete)', null=True, verbose_name='Documentation Completeness'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_onboarding_readiness',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How prepared are our onboarding processes? (1=Not Ready, 5=Fully Ready)', null=True, verbose_name='Onboarding Process Readiness'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_reporting_framework',
            field=models.BooleanField(blank=True, help_text='Is there a reporting framework in place?', null=True, verbose_name='Reporting Framework Available'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_systems_capacity',
            field=models.CharField(blank=True, choices=[('sufficient', 'Sufficient'), ('limited', 'Limited'), ('insufficient', 'Insufficient')], max_length=12, null=True, verbose_name='HR Systems Capacity'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_deliverability',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How confident are you in delivery? (1=Low, 5=High)', null=True, verbose_name='Project Deliverability'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_dependency_management',
            field=models.CharField(blank=True, choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], max_length=10, null=True, verbose_name='Dependency Management'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_resource_clarity',
            field=models.BooleanField(blank=True, help_text='Are resource requirements clearly defined?', null=True, verbose_name='Resource Requirements Clear'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_team_capacity',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('stretched', 'Stretched'), ('overloaded', 'Overloaded')], max_length=10, null=True, verbose_name='Team Capacity'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_timeline_realism',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How realistic are timelines? (1=Unrealistic, 5=Very Realistic)', null=True, verbose_name='Timeline Realism'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_compensation_competitive',
            field=models.CharField(blank=True, choices=[('competitive', 'Competitive'), ('average', 'Average'), ('below', 'Below Market')], max_length=15, null=True, verbose_name='Compensation Competitiveness'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_pipeline_ready',
            field=models.BooleanField(blank=True, help_text='Is there a ready candidate pipeline?', null=True, verbose_name='Candidate Pipeline Ready'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_sourcing_strategy',
            field=models.CharField(blank=True, choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], max_length=10, null=True, verbose_name='Sourcing Strategy Effectiveness'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_talent_availability',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How available is qualified talent in the market? (1=Scarce, 5=Abundant)', null=True, verbose_name='Market Talent Availability'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_time_to_hire',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How quickly can we fill this position? (1=Very Slow, 5=Very Fast)', null=True, verbose_name='Time-to-Hire Estimate'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('job_role', 'Job Role'), ('diagnostic_submission', 'Diagnostic Submission')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('diagnostic_submitted', 'Diagnostic Submitted'), ('final_decision_generated', 'Final Decision Generated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
