# Generated by Django 4.2.28 on 2026-02-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0006_diagnosticsubmission_q_ceo_board_alignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_created', 'Job Role Created'), ('job_deleted', 'Job Role Deleted'), ('assessment_completed', 'Assessment Completed'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
