# Generated by Django 4.2.28 on 2026-02-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0007_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('diagnostic_submitted', 'Diagnostic Submitted'), ('final_decision_generated', 'Final Decision Generated'), ('job_role_deleted', 'Job Role Deleted')], max_length=50),
        ),
    ]
