# Generated by Django 4.2.7 on 2026-03-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0010_remove_diagnosticsubmission_q_ceo_change_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_change_management',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How complex is the change management required? (1=Simple, 5=Very Complex)', null=True, verbose_name='Change Management Complexity'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_customer_experience',
            field=models.BooleanField(blank=True, help_text='Will this role significantly improve customer experience?', null=True, verbose_name='Customer Experience Enhancement'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_market_positioning',
            field=models.CharField(blank=True, choices=[('market_leader', 'Market Leader'), ('market_challenger', 'Market Challenger'), ('niche_player', 'Niche Player'), ('cost_leader', 'Cost Leader')], max_length=20, null=True, verbose_name='Market Positioning Strategy'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_stakeholder_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role impact key stakeholders? (1=Negative, 5=Highly Positive)', null=True, verbose_name='Stakeholder Impact Assessment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ceo_talent_attraction',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role enhance talent attraction? (1=No Impact, 5=Significant Enhancement)', null=True, verbose_name='Talent Attraction Power'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_audit_readiness',
            field=models.BooleanField(blank=True, help_text='Does this role support audit readiness?', null=True, verbose_name='Audit Readiness Support'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_cost_reduction',
            field=models.CharField(blank=True, choices=[('significant', 'Significant Reduction'), ('moderate', 'Moderate Reduction'), ('minimal', 'Minimal Reduction'), ('increase', 'Cost Increase')], max_length=12, null=True, verbose_name='Cost Reduction Potential'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_financial_controls',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this affect financial controls? (1=Weakens Controls, 5=Strengthens Controls)', null=True, verbose_name='Financial Controls Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_investment_justification',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How strong is the financial justification? (1=Weak, 5=Very Strong)', null=True, verbose_name='Investment Justification Strength'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cfo_revenue_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How strong is the projected revenue impact? (1=Minimal, 5=Transformative)', null=True, verbose_name='Revenue Impact Projection'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_conflict_resolution',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well will this role support conflict resolution? (1=Hinders, 5=Enhances)', null=True, verbose_name='Conflict Resolution Capability'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_growth_acceleration',
            field=models.BooleanField(blank=True, help_text='Will this role significantly accelerate growth?', null=True, verbose_name='Growth Acceleration Potential'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_innovation_synergy',
            field=models.CharField(blank=True, choices=[('disruptive', 'Disruptive Innovation'), ('incremental', 'Incremental Innovation'), ('supportive', 'Supportive Innovation'), ('maintenance', 'Maintenance Focus')], max_length=12, null=True, verbose_name='Innovation Synergy'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_risk_sharing',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well does this role distribute business risk? (1=Concentrates Risk, 5=Distributes Risk)', null=True, verbose_name='Risk Sharing Balance'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cofounder_workload_distribution',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role affect founder workload distribution? (1=Increases Burden, 5=Reduces Burden)', null=True, verbose_name='Workload Distribution Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_competitive_advantage',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How strongly will this role create competitive advantage? (1=Minimal, 5=Significant)', null=True, verbose_name='Competitive Advantage Creation'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_exit_strategy',
            field=models.BooleanField(blank=True, help_text='Does this role support long-term exit strategy?', null=True, verbose_name='Exit Strategy Alignment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_investment_priority',
            field=models.CharField(blank=True, choices=[('critical', 'Critical Investment'), ('high', 'High Priority'), ('moderate', 'Moderate Priority'), ('optional', 'Optional Investment')], max_length=12, null=True, verbose_name='Investment Priority Level'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_market_opportunity',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How significant is the market opportunity this role addresses? (1=Limited, 5=Transformative)', null=True, verbose_name='Market Opportunity Assessment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_scalability_impact',
            field=models.CharField(blank=True, choices=[('local', 'Local Impact'), ('regional', 'Regional Impact'), ('national', 'National Impact'), ('global', 'Global Impact')], max_length=15, null=True, verbose_name='Scalability Impact'),
        ),
    ]
