# Generated by Django 4.2.7 on 2026-03-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0011_diagnosticsubmission_q_ceo_change_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_continuous_improvement',
            field=models.BooleanField(blank=True, help_text='Will this role drive continuous improvement?', null=True, verbose_name='Continuous Improvement Driver'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_cost_optimization',
            field=models.CharField(blank=True, choices=[('significant', 'Significant Savings'), ('moderate', 'Moderate Savings'), ('minimal', 'Minimal Savings'), ('investment', 'Requires Investment')], max_length=15, null=True, verbose_name='Cost Optimization Opportunity'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_customer_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this affect customer satisfaction? (1=Negative, 5=Highly Positive)', null=True, verbose_name='Customer Satisfaction Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_operational_risk',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='What is the operational risk level? (1=High Risk, 5=Low Risk)', null=True, verbose_name='Operational Risk Assessment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_coo_service_delivery',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role impact service delivery? (1=Degrades, 5=Significantly Improves)', null=True, verbose_name='Service Delivery Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_architecture_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role impact system architecture? (1=Minimal, 5=Transformative)', null=True, verbose_name='Architecture Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_delivery_velocity',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this affect delivery velocity? (1=Slows Down, 5=Speeds Up)', null=True, verbose_name='Delivery Velocity Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_quality_assurance',
            field=models.BooleanField(blank=True, help_text='Will this role significantly improve QA processes?', null=True, verbose_name='Quality Assurance Enhancement'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_security_posture',
            field=models.CharField(blank=True, choices=[('significant', 'Significant Enhancement'), ('moderate', 'Moderate Enhancement'), ('minimal', 'Minimal Enhancement'), ('risk', 'Security Risk')], max_length=12, null=True, verbose_name='Security Posture Enhancement'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_cto_team_capability',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much will this enhance team capabilities? (1=Minimal, 5=Significant)', null=True, verbose_name='Team Capability Enhancement'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_business_value',
            field=models.BooleanField(blank=True, help_text='Is the business value clearly defined and measurable?', null=True, verbose_name='Clear Business Value'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_innovation_potential',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How innovative is this project? (1=Incremental, 5=Breakthrough)', null=True, verbose_name='Innovation Potential'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_scope_clarity',
            field=models.CharField(blank=True, choices=[('crystal_clear', 'Crystal Clear'), ('well_defined', 'Well Defined'), ('somewhat_clear', 'Somewhat Clear'), ('unclear', 'Unclear')], max_length=15, null=True, verbose_name='Scope Definition Clarity'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_stakeholder_management',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How complex is stakeholder management? (1=Simple, 5=Very Complex)', null=True, verbose_name='Stakeholder Management Complexity'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_ph_success_probability',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='What is the probability of project success? (1=Low, 5=Very High)', null=True, verbose_name='Project Success Probability'),
        ),
    ]
