# Generated by Django 4.2.7 on 2026-03-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0012_diagnosticsubmission_q_coo_continuous_improvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_diversity_inclusion',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this impact D&I initiatives? (1=Negative, 5=Highly Positive)', null=True, verbose_name='Diversity & Inclusion Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_employee_engagement',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this affect employee engagement? (1=Negative, 5=Highly Positive)', null=True, verbose_name='Employee Engagement Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_legal_compliance',
            field=models.BooleanField(blank=True, help_text='Does this role support legal compliance requirements?', null=True, verbose_name='Legal Compliance Support'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_succession_planning',
            field=models.CharField(blank=True, choices=[('critical', 'Critical for Succession'), ('important', 'Important for Succession'), ('supportive', 'Supportive to Succession'), ('no_impact', 'No Succession Impact')], max_length=15, null=True, verbose_name='Succession Planning Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hr_workforce_planning',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How well does this align with workforce planning? (1=Misaligned, 5=Perfectly Aligned)', null=True, verbose_name='Workforce Planning Alignment'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_automation_potential',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much automation potential exists? (1=Minimal, 5=Significant)', null=True, verbose_name='Process Automation Potential'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_data_analytics',
            field=models.CharField(blank=True, choices=[('advanced', 'Advanced Analytics'), ('intermediate', 'Intermediate Analytics'), ('basic', 'Basic Analytics'), ('none', 'No Analytics')], max_length=12, null=True, verbose_name='HR Analytics Capability'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_knowledge_transfer',
            field=models.BooleanField(blank=True, help_text='Is there a knowledge transfer framework in place?', null=True, verbose_name='Knowledge Transfer Framework'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_policy_impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role impact policy development? (1=Minimal, 5=Significant)', null=True, verbose_name='Policy Development Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_hre_vendor_management',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How complex is vendor management? (1=Simple, 5=Very Complex)', null=True, verbose_name='Vendor Management Complexity'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_candidate_experience',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this improve candidate experience? (1=No Impact, 5=Significant Enhancement)', null=True, verbose_name='Candidate Experience Enhancement'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_employer_brand',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role impact employer brand? (1=Negative, 5=Highly Positive)', null=True, verbose_name='Employer Brand Impact'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_hiring_manager_readiness',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How ready are hiring managers? (1=Unprepared, 5=Fully Prepared)', null=True, verbose_name='Hiring Manager Readiness'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_interview_process',
            field=models.CharField(blank=True, choices=[('simple', 'Simple Process'), ('moderate', 'Moderate Process'), ('complex', 'Complex Process'), ('specialized', 'Highly Specialized')], max_length=12, null=True, verbose_name='Interview Process Complexity'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_rec_market_intelligence',
            field=models.BooleanField(blank=True, help_text='Is sufficient market intelligence available?', null=True, verbose_name='Market Intelligence Available'),
        ),
    ]
