# Generated by Django 4.2.7 on 2026-03-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0013_diagnosticsubmission_q_hr_diversity_inclusion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_competitive_advantage',
        ),
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_exit_strategy',
        ),
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_investment_priority',
        ),
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_market_opportunity',
        ),
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_scalability_impact',
        ),
    ]
