# Generated by Django 4.2.7 on 2026-03-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_app', '0014_remove_diagnosticsubmission_q_founder_competitive_advantage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_equity_consideration',
        ),
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_market_positioning',
        ),
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_resource_priority',
        ),
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_strategic_fit',
        ),
        migrations.RemoveField(
            model_name='diagnosticsubmission',
            name='q_founder_vision_alignment',
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_capital_efficiency',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate ROI (0-3 months)'), ('short_term', 'Short-term ROI (3-6 months)'), ('medium_term', 'Medium-term ROI (6-12 months)'), ('long_term', 'Long-term ROI (12+ months)'), ('strategic', 'Strategic Investment (No direct ROI expected)')], max_length=20, null=True, verbose_name='Capital Efficiency'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_competitive_moat',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How strongly will this role create or strengthen your competitive moat? (1=No Moat, 5=Significant Defensible Moat)', null=True, verbose_name='Competitive Moat Creation'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_market_validation',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How validated is the market opportunity this role addresses? (1=Unvalidated, 5=Highly Validated with Customer Traction)', null=True, verbose_name='Market Opportunity Validation'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_network_effects',
            field=models.BooleanField(blank=True, help_text='Will this role create or strengthen network effects for your business?', null=True, verbose_name='Network Effect Creation'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_risk_mitigation',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much does this role mitigate key business risks? (1=No Risk Mitigation, 5=Eliminates Critical Risk)', null=True, verbose_name='Risk Mitigation Value'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_scalability_leverage',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text="How well does this role scale with business growth? (1=Doesn't Scale, 5=Scales Exponentially)", null=True, verbose_name='Scalability Leverage'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_strategic_options',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much strategic option value does this role create for future opportunities? (1=No Option Value, 5=Significant Strategic Options)', null=True, verbose_name='Strategic Option Value'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_talent_amplification',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much will this role amplify the effectiveness of your existing team? (1=No Amplification, 5=10x Team Effectiveness)', null=True, verbose_name='Talent Amplification Factor'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_time_leverage',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How much will this role leverage your time as founder? (1=Consumes More Time, 5=Frees Up 80%+ of Your Time)', null=True, verbose_name='Founder Time Leverage'),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='q_founder_unit_economics',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How will this role impact your unit economics and profitability? (1=Negative Impact, 5=Significantly Improves Unit Economics)', null=True, verbose_name='Unit Economics Impact'),
        ),
    ]
